services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/race_control
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_for_dev} # Use env var or default for dev
      - NEWS1=${NEWS1} # Pass from host environment
      - NEWS2=${NEWS2} # Pass from host environment
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:17-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=race_control
    ports:
      - "5433:5432"

volumes:
  postgres_data:
